# permissions for end users to edit generators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-dns-manager
    app.kubernetes.io/managed-by: kustomize
  name: dns-generator-editor-role
rules:
- apiGroups:
  - dns.xzzpig.com
  resources:
  - generators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.xzzpig.com
  resources:
  - generators/status
  verbs:
  - get
