apiVersion: dns.xzzpig.com/v1
kind: ClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: kube-dns-manager
    app.kubernetes.io/managed-by: kustomize
  name: clustertemplate-sample
spec:
  template: |
    {{- $Ingress := .Ingress -}}
    {{- $Ns := .GetNamespace -}}
    {{- if eq "true" (index $Ns.Labels "dns.xzzpig.com/public" | default "true") }}
    {{- if eq "nginx" ( $Ingress.Spec.IngressClassName | unPtrStr ) }}
    {{- range $RIdx,$Rule := $Ingress.Spec.Rules }}
    - metadata:
        labels: 
          "dns.xzzpig.com/scope": public
          {{- $Ingress.Labels | toYaml | trim | nindent 6}}
        name: public-{{$Rule.Host | replace "." "-" | kebabcase}}
      spec:
        name: {{$Rule.Host}}
        type: CNAME
        value: "sample.sample.com"
        extra:
          "dns.xzzpig.com/cloudflare/comment": "managed by kube-dns-manager"
    {{- end }}
    {{- end }}
    {{- end }}