apiVersion: dns.xzzpig.com/v1
kind: Template
metadata:
  labels:
    app.kubernetes.io/name: kube-dns-manager
    app.kubernetes.io/managed-by: kustomize
  name: template-sample
spec:
  template: |
    {{- $Ingress := .Ingress -}}
    {{ range $RIdx,$Rule := $Ingress.Spec.Rules }}
    {{- $Service := $Ingress.Service $RIdx 0 }}
    {{- $Endpoints := index $Service.Endpoints 0 }}
    {{- $Pod := index $Endpoints.Pods 0 }}
    - metadata:
        labels: 
          {{- $Ingress.Labels | toYaml | trim | nindent 6}}
        name: {{$Rule.Host | replace "." "-" | kebabcase}}
      spec:
        name: {{$Rule.Host}}
        type: A
        value: {{ index $Pod.Node.Annotations "alpha.kubernetes.io/provided-node-ip" }}
        extra:
          test: 123
    {{- end }}
