apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-dns-manager.fullname" . }}-dns-resourcewatcher-viewer-role
  labels:
  {{- include "kube-dns-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - dns.xzzpig.com
  resources:
  - resourcewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.xzzpig.com
  resources:
  - resourcewatchers/status
  verbs:
  - get