apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-dns-manager.fullname" . }}-controller-manager
  labels:
  {{- include "kube-dns-manager.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}