# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dns.xzzpig.com_generators.yaml
- bases/dns.xzzpig.com_resourcewatchers.yaml
- bases/dns.xzzpig.com_templates.yaml
- bases/dns.xzzpig.com_records.yaml
- bases/dns.xzzpig.com_providers.yaml
- bases/dns.xzzpig.com_clusterproviders.yaml
- bases/dns.xzzpig.com_clustertemplates.yaml
- bases/dns.xzzpig.com_clustergenerators.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_dns_generators.yaml
#- path: patches/cainjection_in_dns_resourcewatchers.yaml
#- path: patches/cainjection_in_dns_templates.yaml
#- path: patches/cainjection_in_dns_records.yaml
#- path: patches/cainjection_in_dns_providers.yaml
#- path: patches/cainjection_in_dns_clusterproviders.yaml
#- path: patches/cainjection_in_dns_clustertemplates.yaml
#- path: patches/cainjection_in_dns_clustergenerators.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
